"""modernization_v9

Revision ID: 6a92b79c556a
Revises: 
Create Date: 2026-05-13 17:01:12.018340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a92b79c556a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # Detect dialect
    bind = op.get_context().bind
    is_sqlite = bind.dialect.name == 'sqlite'
    target_schema = None if is_sqlite else 'sarak_auth'
    json_type = postgresql.JSONB(astext_type=sa.Text()) if not is_sqlite else sa.JSON()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('name', 'system', name='uq_permission_name_system'),
    schema=target_schema
    )
    op.create_index(op.f('ix_sarak_auth_permissions_name'), 'permissions', ['name'], unique=False, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_permissions_system'), 'permissions', ['system'], unique=False, schema=target_schema)
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name', 'system', name='uq_role_name_system'),
    schema=target_schema
    )
    op.create_index(op.f('ix_sarak_auth_roles_name'), 'roles', ['name'], unique=False, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_roles_system'), 'roles', ['system'], unique=False, schema=target_schema)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=50), nullable=True),
    sa.Column('address_complement', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=100), nullable=True),
    sa.Column('preferences', json_type, server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', 'system', name='uq_user_email_system'),
    sa.UniqueConstraint('username', 'system', name='uq_user_username_system'),
    schema=target_schema
    )
    op.create_index(op.f('ix_sarak_auth_users_email'), 'users', ['email'], unique=False, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_users_system'), 'users', ['system'], unique=False, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_users_username'), 'users', ['username'], unique=False, schema=target_schema)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f'{target_schema}.users.user_id' if target_schema else 'users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=target_schema
    )
    op.create_index(op.f('ix_sarak_auth_password_reset_tokens_system'), 'password_reset_tokens', ['system'], unique=False, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False, schema=target_schema)
    op.create_table('role_permissions_map',
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('permission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], [f'{target_schema}.permissions.permission_id' if target_schema else 'permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], [f'{target_schema}.roles.role_id' if target_schema else 'roles.role_id'], ondelete='CASCADE'),
    schema=target_schema
    )
    op.create_table('user_interactions',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', json_type, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f'{target_schema}.users.user_id' if target_schema else 'users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interaction_id'),
    schema=target_schema
    )
    op.create_index(op.f('ix_sarak_auth_user_interactions_module_id'), 'user_interactions', ['module_id'], unique=False, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_user_interactions_system'), 'user_interactions', ['system'], unique=False, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_user_interactions_user_id'), 'user_interactions', ['user_id'], unique=False, schema=target_schema)
    op.create_table('user_roles_map',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sarak_auth.roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f'{target_schema}.users.user_id' if target_schema else 'users.user_id'], ondelete='CASCADE'),
    schema=target_schema
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f'{target_schema}.users.user_id' if target_schema else 'users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    schema=target_schema
    )
    op.create_index(op.f('ix_sarak_auth_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True, schema=target_schema)
    op.create_index(op.f('ix_sarak_auth_user_sessions_system'), 'user_sessions', ['system'], unique=False, schema=target_schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_context().bind
    is_sqlite = bind.dialect.name == 'sqlite'
    target_schema = None if is_sqlite else 'sarak_auth'
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sarak_auth_user_sessions_system'), table_name='user_sessions', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_user_sessions_refresh_token'), table_name='user_sessions', schema='sarak_auth')
    op.drop_table('user_sessions', schema='sarak_auth')
    op.drop_table('user_roles_map', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_user_interactions_user_id'), table_name='user_interactions', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_user_interactions_system'), table_name='user_interactions', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_user_interactions_module_id'), table_name='user_interactions', schema='sarak_auth')
    op.drop_table('user_interactions', schema='sarak_auth')
    op.drop_table('role_permissions_map', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_password_reset_tokens_token_hash'), table_name='password_reset_tokens', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_password_reset_tokens_system'), table_name='password_reset_tokens', schema='sarak_auth')
    op.drop_table('password_reset_tokens', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_users_username'), table_name='users', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_users_system'), table_name='users', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_users_email'), table_name='users', schema='sarak_auth')
    op.drop_table('users', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_roles_system'), table_name='roles', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_roles_name'), table_name='roles', schema='sarak_auth')
    op.drop_table('roles', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_permissions_system'), table_name='permissions', schema='sarak_auth')
    op.drop_index(op.f('ix_sarak_auth_permissions_name'), table_name='permissions', schema='sarak_auth')
    op.drop_table('permissions', schema='sarak_auth')
    # ### end Alembic commands ###
